// GOB CRM service worker (GENERATED by scripts/build-sw.py - do not edit by hand).
// Precaches the whole app at install so it opens with no signal; data still comes
// live from Firebase when there is a connection, and saves made offline wait in the
// app's outbox (localStorage) until the connection is back.
const VERSION = 'gob-crm-1d6eac152a';
const SHELL = ["/", "/assets/apple-touch-icon.png", "/assets/icon-192.png", "/assets/icon-512.png", "/assets/icon-maskable-512.png", "/assets/logo-icon.png", "/assets/logo-text.png", "/assets/logo.png", "/assets/title-block.svg", "/css/app.css?v=29", "/css/configurator.css", "/css/drawing.css", "/css/theme.css?v=13", "/data/catalogue.json", "/data/cladding.json", "/data/components.json", "/data/defaults.json", "/data/email-templates.json", "/data/prices.json", "/index.html", "/js/app.js?v=178", "/js/auth.js?v=1", "/js/bom/gmail-send.js?v=1", "/js/bom/installers.js?v=2", "/js/bom/labour.js?v=12", "/js/bom/orders.js?v=41", "/js/bom/premium-bom.js?v=54", "/js/cloud-storage.js?v=6", "/js/construction.js?v=22", "/js/crm.js?v=8", "/js/drawing-engine.js?v=47", "/js/drawing-pdf/export.js", "/js/email/rich-copy.js", "/js/google-config.js?v=2", "/js/pricing.js", "/js/quote/generator.js?v=3", "/js/quote/logoData.js", "/js/quote/template.js", "/js/ui/component-drag.js?v=2", "/lib/firebase/firebase-app-compat.js", "/lib/firebase/firebase-auth-compat.js", "/lib/firebase/firebase-firestore-compat.js", "/lib/firebase/firebase-storage-compat.js", "/lib/jspdf.min.js", "/lib/vue.global.prod.js", "/manifest.webmanifest"];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then(async (c) => {
    const results = await Promise.allSettled(SHELL.map((u) => c.add(new Request(u, { cache: 'reload' }))));
    const failed = results.map((r, i) => (r.status === 'rejected' ? SHELL[i] : null)).filter(Boolean);
    if (failed.length) console.warn('[sw] not cached:', failed);
  }).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // Firebase, Google fonts etc. go straight through
  if (url.pathname.startsWith('/api/')) return;
  // Network first (deploys show up immediately), cache as the offline fallback.
  e.respondWith(fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); }
    return res;
  }).catch(() => caches.match(req, { ignoreSearch: false }).then((hit) => hit
    || caches.match(req, { ignoreSearch: true })
    || (req.mode === 'navigate' ? caches.match('/index.html') : undefined))));
});
