#!/usr/bin/env python3
"""Generate sw.js with a full precache list so the app opens with NO signal on any
device that has installed or opened it before (Liam 20 Sep 2026). Run before every
deploy:  python3 scripts/build-sw.py"""
import re, os, hashlib, json
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
html=open('index.html').read()
urls=set(['/', '/index.html', '/manifest.webmanifest'])
for m in re.finditer(r'(?:src|href)="((?:lib|css|js|assets|data)/[^"]+)"', html): urls.add('/'+m.group(1))
# crawl ES module imports from js/app.js
seen=set(); stack=[m.group(1) for m in re.finditer(r'src="(js/[^"]+)"', html)]
while stack:
    u=stack.pop(); path=u.split('?')[0]
    if path in seen or not os.path.exists(path): continue
    seen.add(path); urls.add('/'+u)
    src=open(path).read()
    for im in re.finditer(r"""from\s+['"](\.{1,2}/[^'"]+)['"]""", src):
        rel=im.group(1); base=os.path.dirname(path)
        norm=os.path.normpath(os.path.join(base, rel.split('?')[0]))
        q='?'+rel.split('?')[1] if '?' in rel else ''
        stack.append(norm+q)
# data + assets the app fetches at runtime
for d in ('data','assets'):
    for f in sorted(os.listdir(d)):
        if f.endswith(('.json','.png','.svg')): urls.add(f'/{d}/{f}')
for f in sorted(os.listdir('lib/firebase')): urls.add('/lib/firebase/'+f)
shell=sorted(urls)
h=hashlib.sha1()
for u in shell:
    p=u.split('?')[0].lstrip('/') or 'index.html'
    if os.path.isfile(p): h.update(open(p,'rb').read())
version='gob-crm-'+h.hexdigest()[:10]
sw=f"""// GOB CRM service worker (GENERATED by scripts/build-sw.py - do not edit by hand).
// Precaches the whole app at install so it opens with no signal; data still comes
// live from Firebase when there is a connection, and saves made offline wait in the
// app's outbox (localStorage) until the connection is back.
const VERSION = '{version}';
const SHELL = {json.dumps(shell)};
self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(VERSION).then(async (c) => {{
    const results = await Promise.allSettled(SHELL.map((u) => c.add(new Request(u, {{ cache: 'reload' }}))));
    const failed = results.map((r, i) => (r.status === 'rejected' ? SHELL[i] : null)).filter(Boolean);
    if (failed.length) console.warn('[sw] not cached:', failed);
  }}).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', (e) => {{
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
}});
self.addEventListener('fetch', (e) => {{
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // Firebase, Google fonts etc. go straight through
  if (url.pathname.startsWith('/api/')) return;
  // Network first (deploys show up immediately), cache as the offline fallback.
  e.respondWith(fetch(req).then((res) => {{
    if (res.ok) {{ const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); }}
    return res;
  }}).catch(() => caches.match(req, {{ ignoreSearch: false }}).then((hit) => hit
    || caches.match(req, {{ ignoreSearch: true }})
    || (req.mode === 'navigate' ? caches.match('/index.html') : undefined))));
}});
"""
open('sw.js','w').write(sw)
print(version, len(shell), 'urls')
